### PR TITLE
Send messages in log file if DISCORD_TOKEN is not specified

### PR DESCRIPTION
**Pull request by believer-ufa**
I think what we do not want send messages to Discord channels while we in local development environment, i suggest send messages just in log file if DISCORD_TOKEN is not specified.

### CODE REVIEW

**Comment by xHeinrich** [comment]
You can use a development server for this as discord servers can be created easily and for free.

**Comment by believer-ufa** [comment]
@xHeinrich now we have 9 different channels on our discord server for different types os notifications on our project) We using discord chats as logs of events in project.

Its normal suggest from you, but i think placing all messages to log is simple and reasonable alternative.

Anyway, i created own `DiscordChannel` class in our project. I decided to just share with you a proposal that could make life easier for you

**Comment by believer-ufa** [comment]
If you think it is not nesessary to approve - cancel this pull request) I understand.

**Comment by dmyers** [comment]
Couldn't you just not use the channel on local inside the `via()` function on your notification class?

**Pull request closed without merging**
