### PR TITLE
PHP 8.0 Support

### LINKED ISSUE #47: PHP 8.0 support
Package doesn't support PHP 8.0

### PR DESCRIPTION
**Pull request by xHeinrich**
As far as I can see this was all that was required. Closes #47

### CODE REVIEW

**Comment by dmyers** [comment]
Is there anyone out there, @owenvoke?

**Comment by owenvoke** [comment]
This looks ok, there was a change between v1.3 and v1.4 of Websocket PHP that added PSR-3 Logger support which appears to break the tests on stable, however I think my last PRs didn't resolve this and we're still merged.

As for the PHP 8 ones failing, Ocular doesn't support PHP 8, so will need to be disabled in the CI workflow. Here's an example of how to do that https://github.com/spatie/dns/commit/f9c3ed55dbbbedbbc1a145890db3232dce9757ad (which would get the PHP 8 lowest workflow passing). :+1:

Just a note, I'm not a maintainer of this project, so I can't really help much.

**Comment by xHeinrich** [comment]
Fixed up the ocular issue. Will take a look into the Websocket PHP tomorrow and see if I can get anywhere with it.

**Comment by Djenkaa** [comment]
@atymic Could you solve this problem?

**Comment by atymic** [comment]
I'll merge it now, as it seems a few people are waiting. Could someone take a look at the tests when they have a chance please?
Thanks!

**Pull request merged**
